# Generated by Django 2.1.5 on 2019-01-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_test_app', '0004_auto_20190121_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='poll_test_app.Poll'),
        ),
    ]
