# Generated by Django 2.1.5 on 2019-01-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_test_app', '0005_auto_20190122_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='slug_option',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='slug_poll',
        ),
    ]
